version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: LojaAmigurumi_container
    environment:
      - POSTGRES_DB=LojaAmigurumi
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"